- Cargo.toml
- src/thegraph/mod.rs
[Alloy](https://www.paradigm.xyz/2023/06/alloy) is the foundation for a rewrite of ethers-rs. It's primitive types (especially `FixedBytes`) are much nicer to work with. This also fixes up some impls that I missed when switching to ethers.
> feat: switch to alloy-primitives

- .github/workflows/ci.yml
- .gitignore
This PR updates the CI workflow with the latest GH action versions (e.g., the checkout action) and uses the same actions used in other edge & node rust projects (e.g., rust toolchain and cargo cache).
Additionally, this PR updates the `.gitignore` file.
> chore(ci): update ci workflow

- .github/workflows/ci.yml
- Cargo.toml
- graphql/Cargo.toml
- graphql/README.md
- graphql/src/graphql.rs
- graphql/src/http.rs
- graphql/src/lib.rs
- toolshed/src/lib.rs
As discussed and agreed in a Slack discussion:
> [...]
> something as involved as a GraphQL parser probably should be it’s own crate as well.
So, in this PR:
Additionally, these changes align with the GraphQL client work in #9.
> chore(graphql): segregate graphql toolshed module

- toolshed/src/url.rs
Cherry-picked changes from #9.
> docs(toolshed): document url wrapper type

- toolshed/Cargo.toml
Set `toolshed` crate's MSRV (Minimum Supported Rust Version) to 1.65.0 after determining it using [the `cargo-msrv` command](https://github.com/foresterre/cargo-msrv):
```
$ cargo msrv
...
Check for toolchain '1.63.0-x86_64-unknown-linux-gnu' failed with:
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Updating crates.io index                                                                                                                                                          │
│  Downloading crates ... …
```
> chore(toolshed): set crate msrv to 1.65.0

- Cargo.toml
- toolshed/Cargo.toml
- toolshed/src/thegraph/attestation.rs
- toolshed/src/thegraph/mod.rs
This is intended to replace the separate implementations of attestation creation & verification across the new Rust indexer-service, TS indexer, gateway, fisherman, etc. A test is included to check backward compatibility with attestations generated by the TS indexer-native implementation, which uses [graphprotocol/eip-712-derive](https://github.com/graphprotocol/eip-712-derive).
> feat(attestation): add attestation module

- toolshed/Cargo.toml
- toolshed/src/thegraph/mod.rs
This adds support for decoding/encoding to and from hex strings in addition to IPFS hashes / CIDv0.
Introducing a dedicated `DeploymentIdError` type makes this a breaking change, but perhaps we're ok with that given the benefits.
The reason this is useful is that in various places we store deployment IDs as hex strings (e.g. in the indexer software). Instead of explicitly handling these cases on one-off basis, the changes introduced here allow to treat them all the same.
> feature: improve DeploymentId encoding/decoding

- .github/renovate.json5
This PR updates Renovate bot's configuration:
> chore(ci): make renovate bot pin github actions versions

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- graphql-http/Cargo.toml
- graphql-http/README.md
- graphql-http/src/compat.rs
- graphql-http/src/graphql.rs
- graphql-http/src/http.rs
- graphql-http/src/http/request.rs
- graphql-http/src/http/response.rs
- graphql-http/src/http_client.rs
- graphql-http/src/lib.rs
- graphql-http/tests/assets/queries.graphql
- graphql-http/tests/assets/schema.graphql
- graphql-http/tests/it_graphql_http_client.rs
- graphql-http/tests/it_graphql_http_client_graphql_client.rs
- graphql-http/tests/it_graphql_http_client_graphql_parser.rs
It is well-known that we have multiple handwritten re-implementations of a _reqwest_ based GraphQL-over-HTTP client. Additionally, most existing crates add an undesired overhead (e.g., schema file-based code generation).
This PR introduces a minor, GraphQL-over-HTTP spec-compliant, _reqwest_ extension trait.
> feat(graphql): add graphql-over-http client

- graphql-http/src/http/response.rs
This is useful when proxying requests from e.g. indexer-service to graph-node and wanting to send any errors back to the client.
> feat: derive serialize for response errors

- README.md
- graphql-http/Cargo.toml
- graphql/Cargo.toml
- graphql/src/lib.rs
This PR batches the following changes:
Once these changes are merged, the `graphql-v0.2.0` and `graphql-http-v0.1.1` tags will be created.
> fix graphql-http feature issue and deprecate graphql crate http module

- Cargo.toml
- README.md
- thegraph/Cargo.toml
- thegraph/README.md
- thegraph/src/client.rs
- thegraph/src/client/queries.rs
- thegraph/src/client/subgraph_client.rs
- thegraph/src/lib.rs
- thegraph/src/types.rs
- thegraph/src/types/attestation.rs
- thegraph/src/types/block_pointer.rs
- thegraph/src/types/deployment_id.rs
- thegraph/src/types/subgraph_id.rs
- thegraph/tests/it_subgraph_client.rs
- toolshed/src/lib.rs
This PR introduces the `thegraph` crate.
> feat(thegraph): add thegraph crate

- thegraph/src/types.rs
- thegraph/src/types/poi.rs
This small PR adds the POI (as a type alias) to the `thegraph` crate well-known types module.
> feat(thegraph): add proof-of-indexing to the types module

- graphql-http/Cargo.toml
- graphql-http/src/compat.rs
- graphql-http/src/http/request.rs
The `async-graphql` is another rust GraphQL crate we use in our projects. 
This PR adds a compatibility shim, gated by the `compat-async-graphql` feature, so one can use an `async_graphql::Request` with the Reqwest-based client.
> feat(graphql-http): add async-graphql request compat shim

- Cargo.lock
- thegraph/Cargo.toml
- thegraph/src/lib.rs
- thegraph/src/subscriptions.rs
- thegraph/src/subscriptions/auth.rs
- thegraph/src/types/attestation.rs
- thegraph/src/types/primitives.rs
I am currently enhancing the `thegraph` crate to make it compatible with both the edge and node projects, both internally and externally. A crucial element that needs attention is the parsing and generation of Subscription tickets. 
By incorporating the subscription ticket generation, parsing, and validation functionality into the `thegraph` crate, users can seamlessly utilize it alongside the `subgraph_client` for querying any subgraph.
> feat(thegraph): add support for subscription payments ticket

- thegraph/src/subscriptions/auth.rs
This follow-up PR extends the Subscriptions Auth token with support for serialization and deserialization of the "extra" claims:
> [!NOTE]
> The naming of the `chain_id` field is an API-breaking change. Upgrading the dependency will require changes in the code using this crate.
>
> * Instead of relying on the struct fields, one should use the new claims field accessor functions, i.e., use either `claims.chain()` or `claims.chain_id()` instead of accessing the `claims.chain` field directly.
This is a follow-up PR of #60
> feat(thegraph): serialize and deserialize subscription extra auth token claims

- Cargo.lock
- thegraph/Cargo.toml
As we are not using a unique version release schema for the crates in this repository, the `path` dependency specifier cannot be used as it can cause dependency version conflicts.
This PR reverts the dependency version specifier changes to use the `git` and `tag` pair. Additionally, it updates the `toolshed` utility crate version to the latest version, v0.5.0.
--- 
From https://github.com/edgeandnode/graph-gateway/pull/478:
> > [!WARNING]
> > Using the latest version (or the `main` branch), probably unstable, is discouraged as it introduces an implicit, uncontrolled, and nontraceable dependency change.
> >
> > It is preferable to use a git tag (or git revision hash) so the version upgrade is traced as part of the development process in the git history, allowing to revert the dependency …
> chore(toolshed): pin crate git dependencies

- .github/workflows/ci.yml
To optimize the build cache hits, these changes merge all jobs under a single CI job: `test`
> chore(ci): merge all ci jobs into a single job

- Cargo.lock
- Cargo.toml
- LICENSE
- thegraph-core/Cargo.toml
- thegraph-core/README.md
- thegraph-core/src/lib.rs
This PR introduces a placeholder crate module in the repo to gradually migrate to the `<namespace>-*` naming schema to publish the crates in _crates.io_.
> [!NOTE]
> An empty version of the `thegraph-core` crate with version v0.0.0 has been manually published to the _crates.io_ repository. This is a placeholder to reserve the crate name.
>
> The `thegraph` crate name has also been reserved in _crates.io_ for future usage.
> chore(thegraph-core): add crate placeholder

- thegraph-core/src/client/subgraph_client.rs
`send_paginated_query` would panic at `query_block.unwrap()` when the first response is empty.
> fix(subgraph_client): avoid panic on missing query block

- thegraph-core/src/client/queries.rs
- thegraph-core/src/client/subgraph_client.rs
- thegraph-core/tests/it_subgraph_client.rs
I had to wrap the subgraph client instance with a `Mutex` in the gateway's network module due to the "latest_block" client's internal state. This is causing lock contention and prevents multiple paginated queries from being run concurrently.
Making the internal state atomic and wrapping it in an `Arc` should fix the limitation.
> feat(thegraph-core): make subgraph client cloneable

- thegraph-core/Cargo.toml
- thegraph-core/src/client/subgraph_client.rs
- thegraph-core/tests/it_subgraph_client.rs
Using _tracing_'s `Span::entered()` was making the futures not `Send`. 
From [_tracing_ docs](https://docs.rs/tracing/latest/tracing/struct.Span.html#method.entered):
> **Note:** The returned [EnteredSpan](https://docs.rs/tracing/latest/struct.EnteredSpan.html) guard does not implement `Send`. Dropping the guard will exit this span, and if the guard is sent to another thread and dropped there, that thread may never have entered this span. Thus, `EnteredSpans` should not be sent between threads.
> fix(thegraph-core): subgraph_client future does not implement Send trait

- thegraph-core/src/client/queries.rs
- thegraph-core/src/client/subgraph_client.rs
- thegraph-core/tests/it_subgraph_client.rs
Changed the subgraph client behavior from treating an empty paginated query as a special case: The `PaginatedQueryError::EmptyResponse` is no longer returned. Instead, an empty vector is returned.
This PR resolves #229
> fix(thegraph-core): return on empty results response

- thegraph-core/src/types.rs
- thegraph-core/src/types/allocation_id.rs
- thegraph-core/src/types/indexer_id.rs
When interacting with the https://github.com/graphprotocol/graph-network-subgraph, important entities such as an indexer or an allocation are uniquely identifiable by their Ethereum address. We are using extensively the `alloy_primitives::Address` type to represent this `id` entity field.
By wrapping the `Address` type in a "new-type wrapper" type, we can leverage Rust's type system to get type guarantees across the codebase. This makes the code more readable and removes the possibility of misusing the APIs.
> feat(thegraph-core): add allocation ID and indexer ID new-types

- thegraph-core/src/types/allocation_id.rs
- thegraph-core/src/types/deployment_id.rs
- thegraph-core/src/types/indexer_id.rs
- thegraph-core/src/types/subgraph_id.rs
In this PR:
This PR supersedes #271
> fix(thegraph-core): fix allocation and indexer ID fmt implementations

- thegraph-core/src/types/poi.rs
This PR replaces the POI's type alias with a _new-type_. It implies an API-breaking change; therefore, it will be part of the next major release of the `thegraph-core` crate.
> feat(thegraph-core): add proof of indexing new-type

- Cargo.lock
- thegraph-core/Cargo.toml
- thegraph-core/src/lib.rs
- thegraph-core/src/types.rs
- thegraph-core/src/types/attestation.rs
- thegraph-core/src/types/deployment_id.rs
This PR moves the **core** from the deprecated `ethers-rs` to the `alloy-rs`. It implies an API-breaking change, therefore it will be part of a major release of the `thegraph-core` crate.
This PR is part of the work of https://github.com/edgeandnode/gateway/issues/885
> feat(thegraph-core): migrate to alloy-rs

- Cargo.lock
- thegraph-core/Cargo.toml
- thegraph-core/src/allocation_id.rs
- thegraph-core/src/attestation.rs
- thegraph-core/src/block.rs
- thegraph-core/src/client/queries.rs
- thegraph-core/src/client/subgraph_client.rs
- thegraph-core/src/deployment_id.rs
- thegraph-core/src/indexer_id.rs
- thegraph-core/src/lib.rs
- thegraph-core/src/proof_of_indexing.rs
- thegraph-core/src/subgraph_id.rs
> [!WARNING]
> This PR contains a **BREAKING CHANGES**
> feat(thegraph-core): re-export alloy meta-crate

- Cargo.lock
- thegraph-core/Cargo.toml
- thegraph-core/src/attestation.rs
As one can see in the alloy book, the `sol!` macro must be imported as `use alloy::sol;` to avoid the following error:
```
error[E0432]: unresolved import `alloy_sol_types`
--> thegraph-core/src/attestation.rs:45:1
|
45 | / alloy::sol_types::sol! {
46 | |     /// EIP-712 receipt struct for attestation signing.
47 | |     struct Receipt {
48 | |         bytes32 requestCID;
...  |
51 | |     }
52 | | }
| |_^ no external crate `alloy_sol_types`
|
= note: this error originates in the macro `alloy::sol_types::sol` (in Nightly builds, run with -Z macro-backtrace for more info)
```
See: https://alloy.rs/highlights/the-sol!-procedural-macro.html
> fix(thegraph-core): remove explicit dependency on alloy-sol-types

- Cargo.lock
- thegraph-core/Cargo.toml
This pull request includes a small change to the `thegraph-core/Cargo.toml` file. The change adds a new feature called `alloy-contract` to the list of available features.
* [`thegraph-core/Cargo.toml`](diffhunk://#diff-d1587aa103511335cd0e08621b52b0ad86d5e66656db2261b213d93d80736f77R13): Added the `alloy-contract` feature under the `[features]` section.
> feat(thegraph-core): add alloy-contract feature

- Cargo.lock
- thegraph-core/Cargo.toml
- thegraph-core/src/lib.rs
This pull request includes changes to the `thegraph-core` project to add and manage the `attestation` feature more effectively. The most important changes include adding the `attestation` feature to the default features, updating dependencies, and conditionally exporting the `Attestation` module based on the feature flag.
Feature management:
* [`thegraph-core/Cargo.toml`](diffhunk://#diff-d1587aa103511335cd0e08621b52b0ad86d5e66656db2261b213d93d80736f77L12-R20): Added the `attestation` feature to the default features and defined its dependencies. Updated the `alloy` dependency to remove specific features since they are now managed by the `attestation` feature. [[1]](diffhunk://#diff-d1587aa103511335cd0e08621b52b0ad86d5e66656db2261b213d93d80736f77L12-R20) …
> feat(thegraph-core): gate the attestation module behind a crate feature

- thegraph-core/Cargo.toml
- thegraph-core/src/lib.rs
This pull request includes changes to `thegraph-core` to simplify the feature set and prepare for future updates. The most important changes include modifying the default features in `Cargo.toml` and removing the `Attestation` re-export from `lib.rs`.
Feature set simplification:
* [`thegraph-core/Cargo.toml`](diffhunk://#diff-d1587aa103511335cd0e08621b52b0ad86d5e66656db2261b213d93d80736f77L12-R12): Changed the default features to an empty list, removing `attestation` from the default set.
Code cleanup:
* [`thegraph-core/src/lib.rs`](diffhunk://#diff-47485ed4ac689adc6116c212d831941f5119be76ac36a8d290fa4008d6616f01L17-L20): Removed the `Attestation` re-export, which was previously marked for removal in the next major version release.
> feat(thegraph-core): remove attestation feature from defaults set

- Cargo.lock
- thegraph-core/Cargo.toml
- thegraph-core/src/allocation_id.rs
- thegraph-core/src/deployment_id.rs
- thegraph-core/src/indexer_id.rs
- thegraph-core/src/lib.rs
- thegraph-core/src/proof_of_indexing.rs
- thegraph-core/src/subgraph_id.rs
This pull request adds support for generating fake data in the `thegraph-core` package. The changes include adding a new dependency for the `fake` crate and implementing the `fake::Dummy` trait for several structs to facilitate the creation of fake data.
* [`thegraph-core/Cargo.toml`](diffhunk://#diff-d1587aa103511335cd0e08621b52b0ad86d5e66656db2261b213d93d80736f77R22-R29): Added `fake` as an optional dependency.
* [`thegraph-core/src/allocation_id.rs`](diffhunk://#diff-2e15fb7e306b4c402d0b6243c330954a6c96d1c98d82004d3594a98175119ae9R178-R185): Implemented `fake::Dummy` for `AllocationId` to generate fake data for this struct.
* [`thegraph-core/src/deployment_id.rs`](diffhunk://#diff-27a2f380f335b2b2b698c5d722b5ccc50425f900e99497ae58ea827028f1dcfaR147-R154): Implemented `fake::Dummy` for …
> feat(thegraph-core): add fake-rs support

- thegraph-core/Cargo.toml
- thegraph-core/src/deployment_id.rs
- thegraph-core/src/lib.rs
This pull request includes changes to the `thegraph-core` package to update the feature name for `async-graphql`. The most significant changes involve modifying the feature name in the `Cargo.toml` file, updating the conditional compilation attribute, and adjusting the feature documentation.
Feature name update:
* [`thegraph-core/Cargo.toml`](diffhunk://#diff-d1587aa103511335cd0e08621b52b0ad86d5e66656db2261b213d93d80736f77L21-R21): Changed the feature name from `async-graphql-support` to `async-graphql`.
* [`thegraph-core/src/deployment_id.rs`](diffhunk://#diff-27a2f380f335b2b2b698c5d722b5ccc50425f900e99497ae58ea827028f1dcfaL173-R173): Updated the `#[cfg(feature = "async-graphql-support")]` attribute to `#[cfg(feature = "async-graphql")]`.
* …
> chore(thegraph-core): rename async-graphql support feature

- Cargo.lock
- thegraph-core/Cargo.toml
- thegraph-core/src/attestation.rs
- thegraph-core/src/headers.rs
- thegraph-core/src/headers/graph_attestation.rs
- thegraph-core/src/lib.rs
This pull request includes several changes to the `thegraph-core` package, focusing on supporting HTTP headers and enhancing the attestation functionality. The most significant changes include adding a new `headers` module, implementing a `GraphAttestation` header, and updating dependencies.
* **New Headers Module:**
- Added a new `headers` module to manage common HTTP _typed headers_ used across The Graph network services. (`thegraph-core/src/headers.rs`)
- Introduced the `GraphAttestation` header within the new `headers` module, which can handle JSON-encoded `Attestation` structs. (`thegraph-core/src/headers/graph_attestation.rs`)
* **Attestation Enhancements:**
- Added support for generating fake `Attestation` data using the `fake` crate. (`thegraph-core/src/attestation.rs`)
> feat(thegraph-core): add graph-attestation http header

- thegraph-core/src/attestation.rs
This pull request includes an addition to the `thegraph-core/src/attestation.rs` file to support the creation of fake `Attestation` objects for testing purposes. The most important change is the implementation of the `fake::Dummy` trait for the `Attestation` struct.
Enhancements for testing:
* [`thegraph-core/src/attestation.rs`](diffhunk://#diff-da19c1761e5c3cd0d98dcc2ffe1b1b2b8d87d9f7840d21cff67c8d4cef3b8ba9R172-R185): Implemented the `fake::Dummy` trait for the `Attestation` struct to allow the creation of fake `Attestation` objects using the `fake` crate. This includes generating random values for `request_cid`, `response_cid`, `deployment`, `r`, `s`, and `v` fields.
> feat(thegraph-core): implement fake trait for attestation type

- thegraph-core/Cargo.toml
- thegraph-core/README.md
This pull request includes updates to the `thegraph-core` crate, specifically addressing a version upgrade and a typo fix.
* [`thegraph-core/Cargo.toml`](diffhunk://#diff-d1587aa103511335cd0e08621b52b0ad86d5e66656db2261b213d93d80736f77L9-R9): Updated the `rust-version` from "1.79.0" to "1.81.0".
> chore(thegraph-core): update msrv to 1.81.0

- README.md
This pull request includes an update to the `README.md` file to enhance the documentation of crates by adding links to their documentation on `docs.rs`.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L12-R16): Added a new column to the crates table with links to the documentation on `docs.rs` for `thegraph-core`, `thegraph-client-subgraphs`, and `thegraph-graphql-http`.
> chore: add docs.rs link to README.md

- Cargo.toml
- thegraph-client-subgraphs/Cargo.toml
- thegraph-graphql-http/Cargo.toml
- thegraph-graphql-http/src/compat.rs
- thegraph-graphql-http/src/http_client.rs
- thegraph-graphql-http/src/lib.rs
- thegraph-graphql-http/tests/it_graphql_http_client.rs
- thegraph-graphql-http/tests/it_graphql_http_client_graphql_client.rs
- thegraph-graphql-http/tests/it_graphql_http_client_graphql_parser.rs
This pull request includes several changes to the `thegraph-graphql-http` crate, primarily focusing on renaming features and updating dependencies. The most important changes include renaming feature flags, updating the Rust version, and modifying dependencies to align with the new feature names.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L6-R7): Reordered the members list to ensure `thegraph-graphql-http` is correctly included.
* [`thegraph-client-subgraphs/Cargo.toml`](diffhunk://#diff-0131188349b5afb5c1cb3c66999bd11e519f9bc6932610041912fb37a23c1b36L17-R17): Updated the feature for `thegraph-graphql-http` dependency from `http-client-reqwest` to `reqwest`.
* [`thegraph-graphql-http/Cargo.toml`](diffhunk://#diff-52164e4c58406a76b36472 …
> feat(thegraph-graphql-http): rename features to match optional deps

- thegraph-client-subgraphs/Cargo.toml
This pull request updates the `thegraph-client-subgraphs/Cargo.toml` file to use a newer version of Rust.
* Updated `rust-version` from `1.79.0` to `1.81.0` in the `thegraph-client-subgraphs/Cargo.toml` file.
> chore(thegraph-client-subgraphs): update msrv to 1.81.0

- thegraph-headers/Cargo.toml
- thegraph-headers/src/http_ext.rs
- thegraph-headers/src/lib.rs
This pull request introduces new functionality for handling HTTP headers more type-safely and updates dependencies accordingly. The most significant changes include adding a new extension trait for HTTP builders, updating the `Cargo.toml` to reflect the new dependency, and exposing the new trait in the library's main module.
* [`thegraph-headers/src/http_ext.rs`](diffhunk://#diff-4a4cbbb78c95273e26852ecd5a9a47934bda4fbcf8b68ad88d7e1c3e075b1d9eR1-R73): Introduced the `HttpBuilderExt` trait, which adds the `header_typed` method for both `http::request::Builder` and `http::response::Builder`. This method allows adding typed headers more ergonomically.
> feat(thegraph-headers): add typed headers http builder extension trait

- thegraph-core/src/deployment_id.rs
- thegraph-core/src/subgraph_id.rs
This pull request includes several changes to the `thegraph-core/src/deployment_id.rs` and `thegraph-core/src/subgraph_id.rs` files to improve the handling and conversion of `DeploymentId` and `SubgraphId` types. The most significant changes include adding new trait implementations, removing redundant functions, and modifying test cases.
* Added `From<hex::FromHexError>` implementation for `ParseDeploymentIdError` to handle hex parsing errors more gracefully.
* Introduced new trait implementations for `DeploymentId`, including `AsRef<[u8]>`, `AsRef<[u8; 32]>`, `std::borrow::Borrow<[u8]>`, and `std::ops::Deref` for better interoperability. [[1]](diffhunk://#diff-27a2f380f335b2b2b698c5d722b5ccc50425f900e99497ae58ea827028f1dcfaR74-R105) …
> feat(thegraph-core): add more conversion trait implementations

- thegraph-headers/Cargo.toml
This pull request includes a minor update to the version specification of `thegraph-core` in the `thegraph-headers/Cargo.toml` file. The change simplifies the version number to ensure compatibility with other dependencies.
Version update:
* [`thegraph-headers/Cargo.toml`](diffhunk://#diff-c903765a684c519123d80a693bb92878c05d76cdd61b709635a436fb40a99a59L19-R19): Updated `thegraph-core` version from "0.9.0" to "0.9" to simplify the version specification.
> chore(thegraph-headers): loose dependencies version requirements

- thegraph-client-subgraphs/Cargo.toml
This pull request includes a change to the version of `thegraph-core` in the `thegraph-client-subgraphs/Cargo.toml` file to ensure compatibility with other dependencies.
Dependency update:
* [`thegraph-client-subgraphs/Cargo.toml`](diffhunk://#diff-0131188349b5afb5c1cb3c66999bd11e519f9bc6932610041912fb37a23c1b36L16-R16): Changed the version of `thegraph-core` from "0.9.1" to "0.9" to maintain consistency and compatibility with the project's requirements.
> chore(thegraph-client-subgraphs): loose dependencies version requirements

- thegraph-core/Cargo.toml
- thegraph-core/src/lib.rs
- thegraph-core/src/signed_message.rs
- thegraph-core/src/signed_message/message.rs
- thegraph-core/src/signed_message/signing.rs
This pull request introduces a new EIP-712 message signing and verification feature in the `thegraph-core` package. The most significant changes include adding a new module for signed messages, updating the `Cargo.toml` file to include new dependencies, and providing comprehensive tests for this new functionality.
* **New Feature**: Added `signed-message` to the crate features list.
* **New Module**: Introduced a new module `signed_message` in `thegraph-core/src/lib.rs` with conditional compilation based on the `signed-message` feature.
* **Signed Message Implementation**: Created the `SignedMessage` struct and related functionality in `thegraph-core/src/signed_message.rs`, including signing, verifying, and recovering signer addresses.
* **Message Struct and Traits**: Defined the …
> feat(thegraph-core): add EIP-712 signed message module

- thegraph-core/src/proof_of_indexing.rs
This pull request includes significant changes to the `ProofOfIndexing` implementation in the `thegraph-core` crate. The changes focus on enhancing type conversions and trait implementations for `ProofOfIndexing`.
Key changes include:
* Implemented `AsRef` and `Borrow` traits for `ProofOfIndexing` to allow references to `B256` and byte arrays.
* Implemented `From` and `TryFrom` traits for various conversions to and from `ProofOfIndexing`, including references to byte arrays.
> feat(thegraph-core): add more POI conversion trait implementations

- thegraph-core/src/signed_message.rs
This pull request includes modifying the `thegraph-core/src/signed_message.rs` file to enhance the functionality of the module exports.
Module export changes:
* [`thegraph-core/src/signed_message.rs`](diffhunk://#diff-4b04ff6c1621a5e95daf139e1f94bf9ad52966f6ad7d40808245058afbacc8f6L79-R79): Added `MessageHash` and `SignatureBytes` to the list of exported items from the `message` module.
> fix(thegraph-core): reexport signed message additional types

- thegraph-graphql-http/tests/it_graphql_http_client.rs
This pull request includes changes to the `thegraph-graphql-http/tests/it_graphql_http_client.rs` file to mark several tests as ignored due to the test server being unavailable. These changes ensure the test suite does not fail due to external dependencies.
* `thegraph-graphql-http/tests/it_graphql_http_client.rs`: Added `#[ignore = "Test server unavailable"]` annotation to the following test functions:
* `send_valid_graphql_request_no_variables`
* `send_valid_graphql_request_with_variables`
* `send_invalid_request_document_parsing_failure`
* `send_invalid_request_field_errors_encountered_during_execution_failure`
* `send_invalid_request_operation_cannot_be_determined_failure_null_operation_name`
* `send_invalid_request_operation_cannot_be_determined_failure_invalid_operation_name`
* …
> chore(thegraph-graphql-http): disable tests due to unavailable test dependency

- thegraph-graphql-http/tests/it_graphql_http_client_graphql_client.rs
- thegraph-graphql-http/tests/it_graphql_http_client_graphql_parser.rs
This pull request includes changes to the `thegraph-graphql-http/tests/it_graphql_http_client_graphql_client.rs` file, specifically marking two test functions to be ignored due to the unavailability of the test server.
* [`thegraph-graphql-http/tests/it_graphql_http_client_graphql_client.rs`](diffhunk://#diff-0ab984a935c3a7cd2057ad1133d981826ee1c7bc0aacb9c6052712fcce6797f5R37): Added `#[ignore = "Test server unavailable"]` attribute to the `send_valid_graphql_request_no_variables` test function.
* [`thegraph-graphql-http/tests/it_graphql_http_client_graphql_client.rs`](diffhunk://#diff-0ab984a935c3a7cd2057ad1133d981826ee1c7bc0aacb9c6052712fcce6797f5R106): Added `#[ignore = "Test server unavailable"]` attribute to the `send_valid_graphql_request_with_variables` test function.
> chore(thegraph-graphql-http): disable tests due to unavailable test dependency (II)

- Cargo.lock
- thegraph-core/Cargo.toml
This pull request includes a version upgrade for the `thiserror` dependency in the `thegraph-core/Cargo.toml` file. 
* [`thegraph-core/Cargo.toml`](diffhunk://#diff-d1587aa103511335cd0e08621b52b0ad86d5e66656db2261b213d93d80736f77L37-R37): Updated the `thiserror` dependency from version `1.0` to `2.0`.
> chore(deps): update rust crate thiserror to v2

- thegraph-core/src/allocation_id.rs
- thegraph-core/src/fake_impl.rs
- thegraph-core/src/fake_impl/alloy.rs
- thegraph-core/src/indexer_id.rs
- thegraph-core/src/lib.rs
This pull request introduces a new module for generating random test data using the `fake` crate and updates existing code to utilize this new module.
New module for generating random test data:
* [`thegraph-core/src/fake_impl.rs`](diffhunk://#diff-b35af10ee88df39cebb3f65ae49efa78587d7080fbbae003afbd48789bc6bdacR1-R2): Added a new `alloy` module for implementing the `fake` crate traits.
* [`thegraph-core/src/fake_impl/alloy.rs`](diffhunk://#diff-8a1def3e6956083589e5c207af631cd9adb440d677a2c739af75031c6063608fR1-R126): Implemented the `fake` crate for generating random test data for various `alloy` crate types, including `Address`, `B256`, `PrimitiveSignature`, and `U256`.
Updates to existing code:
* [`thegraph-core/src/allocation_id.rs`](diffhunk://#diff-2e15fb7e306b4c402d0b6243c330954a6c9 …
> feat(thegraph-core): add fake_impl module and alloy fake support

- thegraph-graphql-http/tests/it_graphql_http_client.rs
- thegraph-graphql-http/tests/it_graphql_http_client_graphql_client.rs
- thegraph-graphql-http/tests/it_graphql_http_client_graphql_parser.rs
This pull request updates the test server URL and re-enables several tests in the `thegraph-graphql-http` module. The most important changes include updating the `TEST_SERVER_URL` constant and removing the `ignore` attribute from multiple test functions.
* [`thegraph-graphql-http/tests/it_graphql_http_client.rs`](diffhunk://#diff-1b09c85374e75c8d8d80d25d3ca3777159b23af15c2de7872427e9cde357d29dL18-L21): Updated `TEST_SERVER_URL` to "https://graphql.org/graphql/" from the previous "https://swapi-graphql.netlify.app/.netlify/functions/index".
* [`thegraph-graphql-http/tests/it_graphql_http_client_graphql_client.rs`](diffhunk://#diff-0ab984a935c3a7cd2057ad1133d981826ee1c7bc0aacb9c6052712fcce6797f5L16-R16): Updated `TEST_SERVER_URL` to "https://graphql.org/graphql/" from the previous …
> chore(thegraph-graphql-http): update test server URL

- thegraph-core/src/fake_impl/alloy.rs
This pull request includes a small change to the `thegraph-core/src/fake_impl/alloy.rs` file. The change updates the method used to generate a random value from `rng.gen()` to `rng.random()`.
> fix(thegraph-core): replace rng.gen() with rng.random() to fix the deprecation warning

- Cargo.toml
- graphql/Cargo.toml
- graphql/src/graphql.rs
- thegraph-client-subgraphs/Cargo.toml
- thegraph-client-subgraphs/src/client.rs
- thegraph-client-subgraphs/src/queries/bootstrap.rs
- thegraph-client-subgraphs/src/queries/page.rs
- thegraph-client-subgraphs/src/queries/tests/it_bootstrap_query.rs
- thegraph-client-subgraphs/src/queries/tests/it_page_query.rs
- thegraph-client-subgraphs/src/queries/tests/testlib.rs
- thegraph-client-subgraphs/tests/it_client_subgraphs.rs
- thegraph-core/Cargo.toml
- thegraph-core/src/attestation.rs
- thegraph-core/src/deployment_id.rs
- thegraph-core/src/fake_impl/alloy.rs
- thegraph-core/src/signed_message.rs
- thegraph-core/src/signed_message/signing.rs
- thegraph-core/src/subgraph_id.rs
- thegraph-graphql-http/Cargo.toml
- thegraph-graphql-http/src/http_client.rs
- thegraph-headers/Cargo.toml
This pull request updates the `Cargo.toml` files across multiple projects to use workspace settings for the `edition`, `license`, and `rust-version` fields. This change ensures consistency and simplifies the maintenance of these configurations.
Key changes include:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R10-R13): Added workspace package settings for `edition` and `license`.
Updates to individual project `Cargo.toml` files to use workspace settings:
* [`graphql/Cargo.toml`](diffhunk://#diff-aa8d8a1ff307348f1c44ba39c1d68d74cb82ec6bfbbd5014889329839c98f841L5-R7): Switched to workspace settings for `edition` and `license`, and updated `rust-version` to "1.85.0".
* [`thegraph-client-subgraphs/Cargo.toml`](diffhunk://#diff-0131188349b5af …
> chore: set Rust edition to 2024

- thegraph-core/src/allocation_id.rs
- thegraph-core/src/collection_id.rs
- thegraph-core/src/lib.rs
This PR adds support for collection ids, a new abstraction in Graph Tally used to track payments. This is a generalization of the usage of allocation ids for TAP v1. Collection ids are 32 bytes whereas allocation ids are 20 bytes (or just addresses).
> feat: add collection_id to thegraph-core
